"""Generate frontend TypeScript API types from docs/openapi.yaml."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
OPENAPI = ROOT / "docs" / "openapi.yaml"
OUTPUT = ROOT / "frontend" / "src" / "generated" / "api-types.ts"


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render_types(parse_openapi_schemas()), encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


def parse_openapi_schemas() -> dict[str, Any]:
    module = load_openapi_contract_module()
    data = module.parse_yaml_like(OPENAPI.read_text(encoding="utf-8"))
    components = data.get("components")
    if not isinstance(components, dict):
        raise RuntimeError("docs/openapi.yaml must contain object section components")
    schemas = components.get("schemas")
    if not isinstance(schemas, dict):
        raise RuntimeError("docs/openapi.yaml must contain object section components.schemas")
    return schemas


def load_openapi_contract_module():
    module_path = ROOT / "scripts" / "check_openapi_contract.py"
    spec = importlib.util.spec_from_file_location("check_openapi_contract_for_codegen", module_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"failed to load helper module {module_path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def render_types(schemas: dict[str, Any]) -> str:
    lines = [
        "/* eslint-disable */",
        "// Generated by scripts/generate_frontend_api_types.py from docs/openapi.yaml.",
        "// Do not edit this file directly.",
        "",
    ]
    for name, schema in schemas.items():
        lines.append(f"export type {name} = {type_for_schema(schema)};")
        lines.append("")
    return "\n".join(lines)


def type_for_schema(schema: Any) -> str:
    if schema is None:
        return "unknown"
    if not isinstance(schema, dict):
        return "unknown"
    if "$ref" in schema:
        return ref_name(schema["$ref"])
    if "enum" in schema and isinstance(schema["enum"], list):
        values = schema["enum"]
        return " | ".join(render_literal(value) for value in values) or "never"
    if "oneOf" in schema and isinstance(schema["oneOf"], list):
        base = " | ".join(type_for_schema(item) for item in schema["oneOf"])
        return with_nullable(base, schema)
    if "anyOf" in schema and isinstance(schema["anyOf"], list):
        base = " | ".join(type_for_schema(item) for item in schema["anyOf"])
        return with_nullable(base, schema)
    if "allOf" in schema and isinstance(schema["allOf"], list):
        base = " & ".join(type_for_schema(item) for item in schema["allOf"])
        return with_nullable(base, schema)

    schema_type = normalize_type(schema.get("type"))
    if schema_type == "string":
        return with_nullable("string", schema)
    if schema_type in {"integer", "number"}:
        return with_nullable("number", schema)
    if schema_type == "boolean":
        return with_nullable("boolean", schema)
    if schema_type == "array":
        item_type = type_for_schema(schema.get("items"))
        return with_nullable(f"{item_type}[]", schema)
    if schema_type == "object" or "properties" in schema or "additionalProperties" in schema:
        return with_nullable(object_type(schema), schema)
    return with_nullable("unknown", schema)


def normalize_type(value: Any) -> str | None:
    if isinstance(value, list):
        non_null = [item for item in value if item != "null"]
        return str(non_null[0]) if non_null else None
    if isinstance(value, str):
        return value
    return None


def with_nullable(base: str, schema: dict[str, Any]) -> str:
    schema_type = schema.get("type")
    nullable = schema.get("nullable") is True or (isinstance(schema_type, list) and "null" in schema_type)
    if not nullable:
        return base
    return f"{parenthesize_for_union(base)} | null"


def parenthesize_for_union(value: str) -> str:
    if " | " in value or " & " in value:
        return f"({value})"
    return value


def object_type(schema: dict[str, Any]) -> str:
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    fields: list[str] = []
    if isinstance(properties, dict):
        for name, property_schema in properties.items():
            optional = "" if name in required else "?"
            fields.append(f'  {render_property_name(str(name))}{optional}: {type_for_schema(property_schema)};')

    additional = schema.get("additionalProperties")
    if additional is True:
        fields.append("  [key: string]: unknown;")
    elif isinstance(additional, dict):
        fields.append(f"  [key: string]: {type_for_schema(additional)};")

    if not fields:
        return "Record<string, unknown>"
    return "{\n" + "\n".join(fields) + "\n}"


def render_property_name(name: str) -> str:
    if name.isidentifier():
        return name
    return render_literal(name)


def render_literal(value: Any) -> str:
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if value is True:
        return "true"
    if value is False:
        return "false"
    if value is None:
        return "null"
    return str(value)


def ref_name(ref: str) -> str:
    prefix = "#/components/schemas/"
    if not ref.startswith(prefix):
        raise RuntimeError(f"unsupported ref: {ref}")
    return ref[len(prefix) :]


if __name__ == "__main__":
    raise SystemExit(main())
